---
#
# Installing Java
#

# Install Java

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: install openjdk-11
  become: yes
  apt: name={{item}} state=present
  with_items:
    - openjdk-11-jdk
    - ca-certificates
    
